# docker install
# docker pull postgres
# docker run --name internal -d -p 5432:5432 -e POSTGRES_PASSWORD="1234" postgres

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/internal
      username: postgres
      password: 1234
      minimum-idle: 10
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
